[build]
  base = "frontend"
  command = "npm run build"
  publish = "frontend/.next"

[functions]
  directory = "functions"
  node_bundler = "esbuild"       

[plugins]
  package = "@netlify/plugin-nextjs"
         
              