[build]
  base = "frontend"          
  command = "npm run build"  
  publish = "out"          
  functions = "../functions" 

[functions]
  node_bundler = "esbuild"   

[[redirects]]
  from = "/*"                
  to = "/index.html"         
  status = 200               