[build]
  base = "frontend"            # Set the base directory to frontend
  command = "npm run build"    # Build command
  publish = ".next"            # Publish directory relative to base
  functions = "../functions"   # Functions directory relative to base

[functions]
  node_bundler = "esbuild"     # Use esbuild for serverless function bundling

[[redirects]]
  from = "/*"
  to = "/"
  status = 200
